name: CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true
    - name: Install Powershell
      run: sudo apt-get install -y powershell
    
    - name: Setup NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1.0.2
      with:
        ndk-version: r21
      
    - name: Create ndkpath.txt
      run: echo ${{ steps.setup-ndk.outputs.ndk-path }} > ${GITHUB_WORKSPACE}/ndkpath.txt
      
    - name: QPM Restore
      run: ./qpm-rust restore
    - name: Build
      run: pwsh -Command ./buildQMOD.ps1
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./BeatLeader.qmod
        if-no-files-found: error
